romteurl: http://www.baidu.com

spring:
  cache:
      type: ehcache
      ehcache:
        config: ehcache.xml
  rabbitmq:
    host: 39.106.168.77
    port: 5672
    username: tomcat
    password: 80201288
    virtual-host: MsgCenter

listeningQueue: DeviceMsgQueue

storageExchange:
    name: CacheStorageExchange
    queue: CacheStorageQueue
    routingkey: CacheStorage

devicefocus:
  setting:
  -
    power: 1
    media: 2
    item1: bentipaiyanwendu
    item2: EE
    item3: FF
  -
    power: 1
    media: 1
    item1: DDD
    item2: EEE
    item3: FFF
