logging:
  file: /home/tomcat/apache-tomcat-8.5.8/webapps/datacache.log
  level: error
token:
  user: userToken
  resource: rescToken

spring:
  profiles:
      active: prod
  cache:
    type: ehcache
    ehcache:
      config: ehcache.xml
devicefocus:
  setting:
  -
    power: 0
    media: 0
    item1: lushuiwendu
    item2: jishuiwendu
    item3: zhengqiyali
  -
    power: 1
    media: 1
    item1: zhengqiyali
    item2: chukouyali
    item3: rukouyali