
logging:
  file: /home/tomcat/datacache/webapps/datacache.log
  level: off
romteurl:
 selldevice: http://www.163.com

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: MsgCenter

listeningQueue: DeviceMsgQueue

storageExchange:
    name: CacheStorageExchange
    queue: CacheStorageQueue
    routingkey: CacheStorage
server:
  port: 8081
