logging:
  file: /home/tomcat/datacache/webapps/datacache.log
  level: error

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: tomcat
    password: 80201288
    virtual-host: MsgCenter

listeningQueue: DeviceMsgQueue

storageExchange:
    name: CacheStorageExchange
    queue: CacheStorageQueue
    routingkey: CacheStorage
